---
title: 'Group Project Idea: NEON parasites'
author: "Wynne Moss"
date: "November 12, 2018"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Description
This is a potential group project idea for Data Science.
Overall question: How does rodent community impact risk of Lyme disease?

This data set would use NEON's observational data on tick pathogens and associated rodent communities.

There are two datasets that need to be joined:

1) Tick Pathogen testing from captured ticks (includes testing information for a variety of bloodborne pathogens). I think the Lyme data are the strongest (Borrelia sp.). In the dataset I pulled there are 545 positive ticks out of 57519 tested ticks.

2) Rodent sampling data from the same sites which contains all of the rodent species captured in a given trap night at a site (this is a big data file)

Other data (vegetation structure, habitat type, temperature, etc) could also be correlated but I don't have a good idea how they would relate to tick-borne pathogens.

## Steps for data analysis
Workflow could include:

1) Getting data from NEON's portal (using functions in R) and cleaning up data

2) Summarizing tick prevalences at a site. Response variable would be number infected ticks out of number tested ticks, which could be modeled as a binomial variable

3) Summarizing relevant environmental data at the site level that could predict infected tick prevalence. This could be something like rodent density, abundance of a particular rodent, time of year, location, etc.

## Challenges with dataset
There is repeat sampling (sites are visited more than once) so we need to use some kind of hierarchical structure. Sites are pretty independent from one another but some sites are in the same region (another possible level of nesting). I don't know how patchy the tick vs. rodent abundance data are; e.g. is there associated rodent trapping data with all of the tick testing data? This is easy enough to check on NEON's website. Rodent trapping data is a huge file which will require manipulating and summarizing into relevant statistics.

## Potential questions
1) What sites have the highest prevalence of ticks carrying Borrelia sp.?

2) How variable is Borrelia prevalence over time?

3) Do certain rodent communities enhance risk of Borrelia?



