---
title: "Individual project outline"
author: "Wynne Moss"
date: "October 17, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## About the data

Data are parasite community data, analyzed over time.
Experimental design: visit 10 sites (ponds) 5 times each over the summer (2017). At each visit, collect 10 individuals of each species and dissect.

Explanatory variables:
  * Site: as a random effect
  * visit: as a factor, if it appears non-linear w/r to response variable, or continuous if appears linear
  * Snout-vent length, a measure of body size: as a continuous predictor
  * Standardized snout-vent length, relative to other individuals (negative values are an individual smaller than average): as a continuous predictor
  * Latitude: as a continuous predictor 
  
Response variables:
  * Presence/absence of various parasite species
  * Parasite richness
  * Abundance of a particular parasite species
  * An axis from an ordination, representing a combination of various parasite species

## Data structure
In this case, observations are at the individual amphibian level (each row of the dataframe is one individual, columns are characteristics of that individual, and presence/absence of different parasite species.)
Individuals are nested within populations, within ponds. Visits are crossed within sites.
*BAM - nested: individual within visit within pond*

E.g. Site A was visited 6 times. Amphibian P1020 was dissected at site A, visit 1, and belongs to species P. Amphibian N199 was dissected at site B, visit 2, and belongs to species N.

Visits are non-independent within the same site.

## Questions of interest
1) How does parasite community (or diversity/richness) change over time?
2) Is variation highest between individuals, between host species, or between sites?
*Neat - this is a variance component question*
3) How do host-level traits (size, species, developmental stage) impact parasite community? Do the relative roles of these factors change over time?
*Probably too complicated for now but a single species model will be the start*
4) Are there certain parasite species found together more often than expected by chance?
*We'll get to this sort of question later - hopefully*

